config/routes.rb
MyStudyLog::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :subjects, only: [:create, :destroy]
  resources :marks,    only: [:create, :destroy]
  root 'static_pages#home'
  match '/signup', to: 'users#new',     via: 'get'  
  match '/signin', to: 'sessions#new',  via: 'get'
  match '/signout',to: 'sessions#destroy', via: 'delete'
  match '/statistics',to: 'static_pages#statistics', via: 'get'

end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :subject
  VALID_DATE_REGEX = /\A[a-z]+ [a-z]+ \d{2} \d{4} \d{2}:\d{2}:\d{2}.*\z/i  
  validates :date, presence: true, format: { with: VALID_DATE_REGEX }, :uniqueness => {:scope => :subject_id }
  validates :subject_id, presence: true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :marks, dependent: :destroy
  belongs_to :user
  validates :name, presence: true, length: {maximum: 30}
  validates :name, :uniqueness => {:scope => :user_id }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :subjects, dependent: :destroy

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: {minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :signed_in_user
# before_action :correct_user, only: :destroy

  def create
    events, @save_dates, @save_ids = [], [], []
    events = params[:mark_subjects].split(/\s*,\s*/)
    events.sort!

    @error_message = ""
    @save_message = nil
    current_name = ""
    subject = nil


    if  events.size == 0
      delete_unsaved_subject_marks(current_user)
      set_message
      respond_to do |format|
        format.html { redirect_to current_user }
        format.js
      end
      return
    end

    events.each do |event|
      name , date = event.split(/\s*\|\s*/)
      if name != current_name
        current_name = name
        delete_unsaved_date_marks(subject)
        subject = get_subject_by_name(name)
      end

      if subject
        create_mark(subject, date)
      end
    end

    delete_unsaved_date_marks(subject)
    delete_unsaved_subject_marks(current_user)

    set_message

    respond_to do |format|
      format.html { redirect_to current_user }
      format.js
    end
  end


  def destroy
    @subject.destroy
    redirect_to root_url
  end

  private

    def mark_params
      params.require(:mark).permit(:date)
    end

    def set_message
      if @error_message == ""
        @save_message = 'Saved Calendar Info.'
      else
        @save_message = @error_message
      end    
    end
    
    def get_subject_by_name(name)
        subject = current_user.subjects.find_by(name: name)
        if subject
          @save_ids << subject.id
        else
          @error_message += 'Error: Subject #{name} not found. '
        end
        subject
    end

    def create_mark(subject, date)
      subject.marks.create(date: date)
      @save_dates << date
    end

    def delete_unsaved_date_marks(subject)
      if subject != nil && @save_dates.length > 0
        subject.marks.where.not(date: @save_dates).delete_all
        @save_dates = []
      end
    end

    def delete_unsaved_subject_marks(user)
      user.subjects.where.not(id: @save_ids).each do |sbj|
        sbj.marks.delete_all
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user 
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def statistics
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user, only: :destroy

  def create
    @subject = current_user.subjects.build(subject_params)
    @user = current_user
    if @subject.save
      @message = 'New Subject created!'
    else
      @message = 'Error: Invalid subject name'
    end
    respond_to do |format|
      format.html { redirect_to current_user }
      format.js
    end
  end

  def destroy
    @subject.marks.delete_all
    @subject.destroy
    @delete_message = 'Delete subject'
    @user = current_user

    respond_to do |format|
      format.html { redirect_to current_user }
      format.js
    end
  end

  private

    def subject_params
      params.require(:subject).permit(:name)
    end

    def correct_user
      @subject = current_user.subjects.find_by(id: params[:id])
      redirect_to root_url if @subject.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    if signed_in?
      @subject  = @user.subjects.build
      @mark = @subject.marks.build
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome !"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "My Studylog"
    if page_title.empty?
      base_title
    else
     "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end


  def signed_in_user
    unless signed_in?
#     store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def store_location
    session[:return_to] = request.url
  end

  def current_subject
    
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def get_month_count(marks)
    results = {}
    marks.each do |mark|
      str = change_date_format(mark.date)
      if results[str]
        results[str] += 1
      else
        results[str] = 1
      end
    end
    results
  end
  
  def change_date_format(date)
    parts = []
    parts = date.split(" ")
    str = "#{parts[3]}/#{get_month(parts[1])}"
  end

  def get_month(m)
    months = [" ", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    months.find_index(m)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # 与えられたユーザーのGravatar (http://gravatar.com/) を返す。
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  def have_subject?(user)
    user.subjects.count > 0
  end

  def date_infos(user)
    infos = ""
    user.subjects.each do |subject|
      break if subject.name.nil? 
      marks = subject.marks
      marks.each do |mark|
        break if mark.date.nil?
        infos += "#{subject.name} , #{mark.date}\n"
      end
    end
    infos
  end

end

app/views/layouts/_header.html.erb
<ul class="nav nav-tabs" role="tablist">
  <% if signed_in? %>
    <li><p class="user_name"><%= link_to gravatar_for(current_user), current_user %> <%= link_to current_user.name, current_user %></p></li>
  <% end %>
  <li><%= link_to "Home", root_path %></li>
  <% if signed_in? %>
    <li><%= link_to "Statistics", statistics_path %></li>
    <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
  <% else %>
    <li><%= link_to "Sign in", signin_path %></li>
  <% end %>
  <li><%= link_to "How to use", "http://saj-kz.hatenablog.com/entry/2014/08/06/235320" %></li>
</ul>



app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/marks/create.js.erb
$("#save_mark_message").html("<%= escape_javascript(render('shared/save_mark_message')) %>");
setTimeout('$("#save_message").fadeOut(1000)', 2000);

app/views/shared/_calendar.html.erb
<% if have_subject?(@user) %>
  <div id=calendar>Calendar</div>
<% end %>

app/views/shared/_delete_subject.html.erb
<% if @delete_message %>
  <p id="delete_message" class="flash_message"><%= @delete_message %></p>
<% end %>
<% @user.subjects.each do |subj| %>
  <%= form_for(subj, remote: true, html: { method: :delete }) do |f| %>
    <%= f.submit "delete #{subj.name}", class: "btn btn-large", data: { confirm: 'delete subjects and marks?' } %>
  <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_mark_form.html.erb
<%= form_for(@mark, remote: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= hidden_field_tag "mark_subjects"  %>
  </div>
  <%= f.submit "Save Events", id: "save", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_save_mark_message.html.erb
<% if @save_message %>
  <p id="save_message" class="flash_message"><%= @save_message %></p>
<% end %>

app/views/shared/_subject.html.erb
<% if @message %>
  <p id="subject_message" class="flash_message"><%= @message %></p>
<% end %>
<%= form_for @subject do |f| %>
  <%= f.label :id, "select subject" %>
  <%= f.collection_select :id, @user.subjects, :name, :name %>
<% end %>

app/views/shared/_subject_form.html.erb
<%= form_for(@subject, remote: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label "add new subject" %>
    <%= f.text_field :name %>
    <%= f.submit "create", class: "btn btn-info" %>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>My Studylog</h1>
<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>

app/views/static_pages/statistics.html.erb
<h3><%= "#{current_user.name} have #{current_user.subjects.count} subjects" %></h3>
<div class="row">
  <% current_user.subjects.each do  |subj| %>
  	<div class="col-md-4 col-sm-6">
      <h3><%= "#{subj.name} : #{subj.marks.count}" %></h3>
      <ul class="list-group">
      <% get_month_count(subj.marks).each_pair do |month, val| %>
        <li class="list-group-item"><%= "#{month}" %><span class="badge"><%= "#{val}" %></span></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/subjects/create.js.erb
$("#select_subject").html("<%= escape_javascript(render('shared/subject')) %>");
$("#delete_subject").html("<%= escape_javascript(render('shared/delete_subject')) %>");
setTimeout('$("#subject_message").fadeOut(1000)', 2000);

app/views/subjects/destroy.js.erb
$("#delete_subject").html("<%= escape_javascript(render('shared/delete_subject')) %>");
$("#select_subject").html("<%= escape_javascript(render('shared/subject')) %>");
//$("#calendar_space").html("<%= escape_javascript(render('shared/calendar')) %>");
setTimeout('$("#delete_message").fadeOut(1000)', 2000);

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1" >
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: "Enter user name" %>

      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control", placeholder: "Enter email" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", placeholder: "password" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "password (1 more)" %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% if signed_in? %>
  <div class="container">
    <div class="row">
      <div class="span3">
        <section>
          <%= render 'shared/subject_form' %>
        </section>
        <% if have_subject?(@user) %>
          <div id="select_subject">
            <%= render 'shared/subject' %>
          </div>
        <% end %>
        <div id="save_mark_message">
          <%= render 'shared/save_mark_message' %>
        </div>
        <%= render 'shared/mark_form' %>
        <%= hidden_field_tag 'debug_text' ,  date_infos(@user) %>
        <div id="delete_subject">
          <%= render 'shared/delete_subject' %>
        </div>
      </div>
      <div id="calendar_space" class="span9">
        <%= render 'shared/calendar' %>
      </div>
    </div>
  </div>
<% end %>